jwt:
  secret: 3SiRSHaXtsxyBTG4GPtybzU38DHQgeBIN7LLRr05wvHPstz8nHyYOicCkQ892YA
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        generate_statistics: true
        cache:
          redisson:
            config: redisson-dev.yaml
    show-sql: true